name: Deploy MERN App to AWS EC2

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.60.6.247 << 'EOF'
          cd ~/Portfolio
          # Pull latest changes
          git pull origin main  # Change 'main' if using a different branch

          # Backend setup
          cd backend
          npm install
          # Check if backend process is running, restart if it is, otherwise start it
          if pm2 list | grep -q "backend"; then
            pm2 restart backend
          else
            pm2 start server.js --name backend
          fi

          # Frontend setup
          cd ../frontend
          npm install
          npm run build
          # Check if frontend process is running, restart if it is, otherwise start it
          if pm2 list | grep -q "frontend"; then
            pm2 restart frontend
          else
            pm2 serve build 3000 --name frontend
          fi

          exit
          EOF
